name: get map
on: [push]
jobs:
  get-map:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit-42
    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
    - name: get map
      run: make mu